import '@Blocks/button/button.scss';
import '@Blocks/button-to-send/button-to-send.scss';
import '@Blocks/checkbox-list/checkbox-list.scss';
import '@Blocks/checkbox-list-expandable/checkbox-list-expandable.scss';
import '@Blocks/checkbox-list-expandable/checkbox-list-expandable';
import '@Blocks/comment-block/comment-block.scss';
import '@Blocks/dropdown/dropdown.scss';
import '@Blocks/dropdown/dropdown';
import '@Blocks/dropdown-dates/dropdown-dates.scss';
import '@Blocks/info-block/info-block.scss';
import '@Blocks/input-text/input-text.scss';
import '@Blocks/input-text/input-text';
import '@Blocks/like/like.scss';
import '@Blocks/like/like';
import '@Blocks/link/link.scss';
import '@Blocks/list-block/list-block.scss';
import '@Blocks/pagination/pagination.scss';
import '@Blocks/radiogroup/radiogroup.scss';
import '@Blocks/range-slider/range-slider.scss';
import '@Blocks/rate-btn/rate-btn.scss';
import '@Blocks/rate-btn/rate-btn';
import '@Blocks/toggle-block/toggle-block.scss';
import '@Blocks/toggle-block/toggle-block';
import '@Blocks/topic-label/topic-label.scss';

import '@Blocks/calendar/calendar';

import '@Pages/ui-kit-form-elements/ui-kit-form-elements.scss';
import '@Pages/ui-kit-form-elements/range-slider';
